import * as React from 'react';

interface OutletFooterProps {
  lng: 'en' | 'hu';
}

const footerText = {
  en:
    'Our content is partly or entirely generated by volunteers and may reflect opinions in some cases. Neither the Democrable Community nor the maintenance team undertake any responsibility for the correctness of information displayed including in legal disputes. All content is available under the Creative Commons BY-NC-SA 4.0 license.',
  hu:
    'Tartalmaink részben vagy teljes egészében önkénteseink által készítettek és bizonyos esetekben véleményeket tükröznek. A Democrable Community, valamint a honlap fenntartói az ezekből fakadó jogvitákban nem vállalnak felelősséget. Az összes tartalom a Creative Commons BY-NC-SA 4.0 licensz alatt érhető el.',
  license: '2017-2018; Democrable',
};

export default (props: OutletFooterProps) => (
  <footer className="barlow">
    <hr className="horizontal" />
    <p id="media-footer">
      <br />
      {footerText[props.lng]}
      <br />
      {footerText.license}
    </p>
  </footer>
);
