import * as React from 'react';
import { css } from 'emotion';

interface OutletFooterProps {
  lang: 'en' | 'hu';
}

const footerText = {
  en:
    'Our content is partly or entirely generated by volunteers and may reflect opinions ' +
    'in some cases. Neither the Democrable Community nor the maintenance team undertake ' +
    'any responsibility for the correctness of information displayed including in legal ' +
    'disputes. All content is available under the Creative Commons BY-NC-SA 4.0 license.',
  hu:
    'Tartalmaink részben vagy teljes egészében önkénteseink által készítettek és bizonyos ' +
    'esetekben véleményeket tükröznek. A Democrable Community, valamint a honlap fenntartói ' +
    'az ezekből fakadó jogvitákban nem vállalnak felelősséget. Az összes tartalom a Creative ' +
    'Commons BY-NC-SA 4.0 licensz alatt érhető el.',
  license: '2017-2018; Democrable',
};

const footerStyle = css({
  width: '100%',
  height: 'auto',
  minHeight: '6rem',
  marginTop: '2rem',
  textAlign: 'center',
  backgroundColor: '#f5f5f5',
});

export default (props: OutletFooterProps) => (
  <footer className={`barlow ${footerStyle}`}>
    <hr className="horizontal" />
    <p>
      <br />
      {footerText[props.lang]}
      <br />
      {footerText.license}
    </p>
  </footer>
);
